DELETE http://localhost:8080/api/persons/12

###

POST http://localhost:8080/api/persons
Content-Type: application/json

{
    "name": "brandon",
    "number": 18
}

###
GET http://localhost:8080/info

###
DELETE http://localhost:8080/api/persons/63ae6e166dff2990e2078f5a